id: P881819EC
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1CZ2258
  instance_id: http://purl.bdrc.io/resource/IE1CZ2258
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - འཇུག་འགྲེལ་གསལ་བའི་མེ་ལོང་དང་འཇུག་འགྲེལ་གསལ་བའི་རྒྱན།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P84
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    6fd035b3332e4ca483145be19cb3e785:
      title: པོད ༡་འཇུག་འགྲེལ་གསལ་བའི་མེ་ལོང་དང་འཇུག་འགྲེལ་གསལ་བའི་རྒྱན
      volume_number: 1
      base_file: UT1CZ2258_I1CZ2297_0000.txt
      reference: http://purl.bdrc.io/resource/VLAB53A1055921BFFF
      image_group: I1CZ2297
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1CZ2258
  - http://purl.bdrc.io/resource/MW1CZ2258
  ocr_software: Namsel
created_at: '2021-12-22T10:24:32.110323'
last_modified_at: '2021-12-22T10:24:32.110330'
